package pair

import (
	"fmt"
	"math"
	"math/rand"
)

// PathResult is a walk: the outcomes it chose and what they cost.
type PathResult struct {
	Text       string    `json:"text"`      // the generated bytes
	FullText   string    `json:"full_text"` // prefix and generated bytes
	Units      []int     `json:"units"`     // outcomes, End included when reached
	Cost       float64   `json:"cost"`      // -ln P summed over the steps
	StepCosts  []float64 `json:"step_costs"`
	Traversal  string    `json:"traversal"`
	Mode       string    `json:"mode"`
	ReachedEnd bool      `json:"reached_end"`
	Peak       float64   `json:"peak"` // the fold's highest probability at the first step
}

// Encoder is the tokenizer's view a walk needs: the code of a context.
type Encoder func(context []byte) []int32

// Walk continues a prefix one outcome at a time from the exact fold: the most probable outcome (rng nil), or
// a sample at a temperature. It stops at End, after units outcomes, or, with toEnd, after maxUnits.
func (p *Pair) Walk(prefix []byte, encode Encoder, units int, traversal string, rng *rand.Rand, temperature float64,
	toEnd bool, backoff string, maxUnits int) (PathResult, error) {
	if temperature <= 0 {
		temperature = 1
	}
	if maxUnits <= 0 {
		maxUnits = 4096
	}
	res := PathResult{Traversal: traversal, Mode: "greedy"}
	if rng != nil {
		res.Mode = "sample"
	}
	buf := append([]byte(nil), prefix...)
	for step := 0; ; step++ {
		if toEnd {
			if step >= maxUnits {
				break
			}
		} else if step >= units {
			break
		}
		P, err := p.Fold(encode(buf), traversal, backoff)
		if err != nil {
			return res, err
		}
		x := 0
		if rng == nil {
			for j, v := range P {
				if v > P[x] {
					x = j
				}
			}
		} else {
			x = sample(P, temperature, rng)
		}
		if step == 0 {
			for _, v := range P {
				if v > res.Peak {
					res.Peak = v
				}
			}
		}
		cost := -math.Log(P[x])
		res.Cost += cost
		res.StepCosts = append(res.StepCosts, cost)
		res.Units = append(res.Units, x)
		if x == End {
			res.ReachedEnd = true
			break
		}
		buf = append(buf, byte(x))
	}
	res.Text = string(buf[len(prefix):])
	res.FullText = string(buf)
	return res, nil
}

// sample draws from P sharpened to a temperature.
func sample(P []float64, temperature float64, rng *rand.Rand) int {
	w := make([]float64, len(P))
	sum := 0.0
	for j, v := range P {
		if v > 0 {
			w[j] = math.Pow(v, 1/temperature)
			sum += w[j]
		}
	}
	r := rng.Float64() * sum
	acc := 0.0
	for j, v := range w {
		acc += v
		if r < acc {
			return j
		}
	}
	for j := len(w) - 1; j >= 0; j-- {
		if w[j] > 0 {
			return j
		}
	}
	return 0
}

// Outcomes are a text's outcomes: its bytes then End.
func Outcomes(text []byte) []int {
	out := make([]int, len(text)+1)
	for i, b := range text {
		out[i] = int(b)
	}
	out[len(text)] = End
	return out
}

func (r PathResult) String() string {
	return fmt.Sprintf("%q (cost %.3f, %d units, end %v)", r.Text, r.Cost, len(r.Units), r.ReachedEnd)
}
