"""2NRL on CartPole: learn to fail on purpose, invert, fine-tune.

The three phases of ``two_nrl(bad, good)`` (see ``RadixCyclicNN/README.md``),
carried over from text to control:

1. **negative** - train the policy on *failure*: reward ``-1`` per step, so the
   network is pushed to knock the pole over as fast as it possibly can.  This
   is the "train on garbage" phase, and here the garbage is generated by the
   network itself.
2. **invert** - flip the network (``SineNet.invert``).  Every win becomes a
   loss and every loss becomes a win: the output negates exactly, so the
   action the failure policy most wanted is now the one it least wants.  No
   training happens here and the balancing task has never been seen.
3. **positive** - fine-tune on the real reward with a smaller learning rate,
   the activation parameters at a tenth of it, exactly as ``TrainConfig``
   does (``lr`` / ``act_lr``).

The policy is a :class:`sinenet.SineNet` - the author's sine-wave activation
``a*sin(b*(x-h))+k`` with all four parameters learnable per neuron - trained
with REINFORCE.

Failure delta: venture out as far as we fall fast
-------------------------------------------------
How badly the network is losing sets how far it goes looking for new ways to
lose.  Writing ``L`` for the mean length of the recent failure episodes and
``L_min`` for the physical floor (about 8 steps - the pole cannot be dropped
faster than that), the **failure delta** is::

    delta = clip(L_min / L, 0, 1)

1.0 when we lose as fast as the physics allow, small when we are still
dawdling.  It drives two things, both scaled by the same number:

* **how far out we venture** - the negative phase resets from a ball of
  radius ``delta * MAX_START_RADIUS`` around the origin, drawn *equally in
  every direction* in the normalised state space, so as the network gets
  better at falling over near the upright it ventures further out and has to
  learn how to fall from everywhere.  This also kills the degenerate
  solution: always pushing the same way tips the pole in ten steps from the
  standard reset, and a constant policy inverts into another constant
  policy, proving nothing.  From a state that is already leaning, the
  fastest failure is to shove the cart *away* from the lean - which is
  state-dependent, and whose inverse is the balancing policy.
* **how hard each failure trains** - an episode of its own delta is weighted
  by it, so the worse a failure the harder the network is pushed to
  reproduce it.  This is ``two_nrl``'s ``bad_weights`` ("to blatantly fail on
  purpose") applied per episode instead of per text.

Every evaluation - and the whole positive phase - uses the standard CartPole
reset, so the reported rewards stay comparable to ``ActivationFunctionTest``.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass

import gymnasium as gym
import numpy as np

from sinenet import Adam, SineNet

# CartPole's four observations live on very different scales; this puts them
# on a comparable one before the sine sees them (fixed, not learned).  A
# radius in this space is therefore the same "distance" along every axis.
OBS_SCALE = np.array([1 / 2.4, 1 / 2.0, 1 / 0.21, 1 / 2.0])

MIN_FAIL_STEPS = 8.0      # the floor: CartPole cannot be lost faster than this
MAX_START_RADIUS = 0.8    # normalised units; 1.0 would start on the terminal boundary
SOLVED = 475.0            # CartPole-v1's own threshold

# CartPole ends the episode at either of these; they define the grade below.
THETA_LIMIT = 0.2095
X_LIMIT = 2.4

# Hard safety bounds on a start state, as a fraction of the terminal limits.
START_LIMIT = np.array([0.9 * 2.4, np.inf, 0.85 * 0.2095, np.inf])


@dataclass
class Config:
    hidden: int = 24
    tau: float = 0.2                 # softmax temperature over the sine output
    gamma: float = 0.99
    neg_lr: float = 0.01             # research 2NRL ratio is neg:pos = 5:1
    pos_lr: float = 0.002            # activation params run at lr/10 (TrainConfig)
    neg_entropy: float = 0.02
    pos_entropy: float = 0.01
    neg_batch_steps: int = 400       # failure episodes are ~10 steps long
    pos_batch_steps: int = 2000
    neg_updates: int = 150
    pos_updates: int = 60
    eval_episodes: int = 20
    final_eval_episodes: int = 100
    adaptive_starts: bool = True     # venture out in proportion to the graded loss
    weight_by_delta: bool = True     # two_nrl's bad_weights, per episode
    grading: str = "margin"          # "margin" = |target - achieved|; "speed" = legacy ratio
    seed: int = 0


def margin(obs: np.ndarray) -> float:
    """How far this state is from falling over, ``1`` upright and centred, ``0`` at the edge.

    A *normalised state-space distance* - the same units the venture radius is
    measured in, which is what lets a graded loss be spent directly as a
    distance to explore.
    """
    return float(1.0 - max(abs(obs[2]) / THETA_LIMIT, abs(obs[0]) / X_LIMIT))


def graded_loss(margins: list[float], negative: bool) -> float:
    """The loss of one episode, graded onto ``[0, 1]``: ``|target - achieved|``.

    The negative phase is aiming at margin ``0`` - fall over, now - so its loss
    is simply the margin it actually held: hold 0.6 and you lost by 0.6.  The
    positive phase aims at margin ``1`` and its loss is ``1 - margin``.  Either
    way the number is how far the episode ended up from what was asked of it,
    and *that distance is how far we then venture out, equally in every
    direction*: miss by 0.4 and explore 0.4.

    The loop this closes is self-regulating.  Failing is easy close to the
    edge, so a wide start scores a small loss and pulls the next start back in;
    failing near the upright is slow, scores a large loss and pushes the next
    start out.  The radius settles where the policy still has something left to
    learn, instead of ramping to a hard-coded maximum.
    """
    if not margins:
        return 1.0
    held = float(np.mean(margins))
    return float(np.clip(held if negative else 1.0 - held, 0.0, 1.0))


def failure_delta(mean_length: float) -> float:
    """Legacy ``--grading speed`` delta: a ratio, not a graded loss.

    Kept only for comparison - it saturates at 1 and pins the radius to
    ``MAX_START_RADIUS``, so it stops adapting once failure is mastered.
    """
    if mean_length <= 0:
        return 1.0
    return float(np.clip(MIN_FAIL_STEPS / mean_length, 0.0, 1.0))


# --------------------------------------------------------------------- policy


def policy_probs(net: SineNet, obs: np.ndarray, tau: float, train: bool = False) -> np.ndarray:
    logits = net.forward(obs * OBS_SCALE, train=train) / tau
    logits = logits - logits.max(axis=-1, keepdims=True)
    e = np.exp(logits)
    return e / e.sum(axis=-1, keepdims=True)


def act_greedy(net: SineNet, obs: np.ndarray, tau: float) -> int:
    return int(np.argmax(net.forward(obs[None] * OBS_SCALE, train=False)[0]))


# ------------------------------------------------------------------- rollouts


def venture_state(rng: np.random.Generator, radius: float) -> np.ndarray:
    """A start state ``radius`` out from the origin, equally in every direction.

    The direction is uniform on the unit sphere of the normalised state space
    and the distance *is* the radius, so the network is put exactly as far out
    as its own failure delta says, equally in every direction.  Sampling
    uniformly *inside* the ball instead puts most of the mass back near the
    origin, where a constant push is already almost the fastest way to fall
    (9.4 steps against 8.6) - too small a gap to learn from, and the policy
    collapses to a constant action whose inverse is another constant action.
    Out on the surface at radius 0.8 the gap is 9.9 against 6.8, and the
    state-dependent failure is worth finding.  The result is mapped back to
    real CartPole units and clipped inside the terminal boundary.
    """
    direction = rng.normal(size=4)
    direction /= np.linalg.norm(direction) or 1.0
    state = direction * radius / OBS_SCALE
    return np.clip(state, -START_LIMIT, START_LIMIT)


def reset(env: gym.Env, rng: np.random.Generator, radius: float | None) -> np.ndarray:
    obs, _ = env.reset()
    if radius is not None and radius > 0:
        state = venture_state(rng, radius)
        env.unwrapped.state = state
        obs = np.array(state, dtype=np.float32)
    return obs


def collect(env: gym.Env, net: SineNet, cfg: Config, rng: np.random.Generator,
            min_steps: int, negative: bool, radius: float | None = None) -> dict:
    """Run whole episodes until ``min_steps`` transitions are gathered."""
    obs_buf, act_buf, ret_buf, weight_buf, lengths, losses = [], [], [], [], [], []
    steps = 0
    while steps < min_steps:
        obs = reset(env, rng, radius if negative else None)
        rewards, ep_obs, ep_act, ep_margins = [], [], [], []
        done = False
        while not done:
            probs = policy_probs(net, obs[None], cfg.tau)[0]
            action = int(rng.random() < probs[1])
            nxt, reward, terminated, truncated, _ = env.step(action)
            ep_obs.append(obs)
            ep_act.append(action)
            ep_margins.append(margin(obs))
            # The negative phase's reward *is* the inversion of the task:
            # -1 a step, so a shorter episode is a better one.
            rewards.append(-1.0 if negative else float(reward))
            obs, done = nxt, terminated or truncated
        g, returns = 0.0, np.empty(len(rewards))
        for i in range(len(rewards) - 1, -1, -1):
            g = rewards[i] + cfg.gamma * g
            returns[i] = g
        # The episode's graded loss drives how far we venture next; how well it
        # *hit* the target (1 - loss) drives how hard it trains, which is
        # two_nrl's bad_weights: the worse the failure, the harder it trains.
        loss = (graded_loss(ep_margins, negative) if cfg.grading == "margin"
                else 1.0 - failure_delta(len(rewards)))
        losses.append(loss)
        weight = (1.0 - loss) if (negative and cfg.weight_by_delta) else 1.0
        obs_buf.extend(ep_obs)
        act_buf.extend(ep_act)
        ret_buf.extend(returns)
        weight_buf.extend([weight] * len(rewards))
        lengths.append(len(rewards))
        steps += len(rewards)
    return {
        "obs": np.array(obs_buf) * OBS_SCALE,
        "actions": np.array(act_buf),
        "returns": np.array(ret_buf),
        "weights": np.array(weight_buf),
        "lengths": lengths,
        "graded_loss": float(np.mean(losses)) if losses else 1.0,
    }


def reinforce_update(net: SineNet, opt: Adam, batch: dict, cfg: Config,
                     entropy_beta: float) -> None:
    obs, actions, returns = batch["obs"], batch["actions"], batch["returns"]
    n = len(actions)
    adv = returns - returns.mean()
    std = adv.std()
    if std > 1e-8:
        adv = adv / std
    adv = adv * batch["weights"]

    logits = net.forward(obs, train=True) / cfg.tau
    shifted = logits - logits.max(axis=1, keepdims=True)
    e = np.exp(shifted)
    probs = e / e.sum(axis=1, keepdims=True)
    logp = shifted - np.log(e.sum(axis=1, keepdims=True))

    # policy gradient: d[-logpi(a|s) * A]/dlogits = (probs - onehot) * A
    onehot = np.zeros_like(probs)
    onehot[np.arange(n), actions] = 1.0
    dlogits = (probs - onehot) * adv[:, None]

    # entropy bonus: loss carries -beta*H, and dH/dl_i = -p_i * (log p_i + H)
    entropy = -(probs * logp).sum(axis=1, keepdims=True)
    dlogits += entropy_beta * probs * (logp + entropy)

    opt.step(net.backward(dlogits / (cfg.tau * n)))


# ----------------------------------------------------------------- evaluation


def evaluate(net: SineNet, cfg: Config, episodes: int, seed: int) -> dict:
    """Greedy play from the *standard* CartPole reset."""
    env = gym.make("CartPole-v1")
    totals = []
    for i in range(episodes):
        obs, _ = env.reset(seed=seed + i)
        total, done = 0.0, False
        while not done:
            obs, reward, terminated, truncated, _ = env.step(act_greedy(net, obs, cfg.tau))
            total += reward
            done = terminated or truncated
        totals.append(total)
    env.close()
    t = np.array(totals)
    return {"mean": float(t.mean()), "std": float(t.std()),
            "min": float(t.min()), "max": float(t.max()), "episodes": episodes}


def state_dependence(net: SineNet, cfg: Config) -> dict:
    """Does the policy read the state, or has it collapsed to a constant action?

    Probes a grid of pole angles and angular velocities.  ``majority_action_share``
    of 1.0 means a constant policy (degenerate - its inverse is also constant);
    near 0.5 means the action genuinely depends on which way the pole is going.
    ``anti_balance_agreement`` is how often it pushes *away* from the lean,
    which is the fastest way to fall.
    """
    angles = np.linspace(-0.15, 0.15, 21)
    vels = np.linspace(-1.0, 1.0, 21)
    grid = np.array([[0.0, 0.0, a, v] for a in angles for v in vels])
    choices = net.forward(grid * OBS_SCALE, train=False).argmax(axis=1)
    share = max(np.mean(choices == 0), np.mean(choices == 1))
    lean_right = grid[:, 2] + 0.25 * grid[:, 3] > 0
    anti = float(np.mean(choices[lean_right] == 0))     # leaning right -> push left
    pro = float(np.mean(choices[~lean_right] == 1))     # leaning left  -> push right
    return {"majority_action_share": float(share),
            "anti_balance_agreement": float((anti + pro) / 2)}


# --------------------------------------------------------------------- phases


def run_phase(env, net, opt, cfg, rng, updates, negative, entropy, label, log,
              step_budget: int | None = None):
    recent: list[float] = []
    env_steps = 0
    delta = MAX_START_RADIUS           # first batch: assume we are wholly off target
    radius = MAX_START_RADIUS
    for u in range(updates):
        use_radius = radius if (negative and cfg.adaptive_starts) else None
        batch = collect(env, net, cfg, rng,
                        cfg.neg_batch_steps if negative else cfg.pos_batch_steps,
                        negative, use_radius)
        reinforce_update(net, opt, batch, cfg, entropy)
        env_steps += int(sum(batch["lengths"]))
        recent.extend(batch["lengths"])
        recent = recent[-100:]
        mean_len = float(np.mean(recent))
        if negative:
            # how far we missed by is how far out we look next
            delta = (batch["graded_loss"] if cfg.grading == "margin"
                     else failure_delta(mean_len))
            radius = float(np.clip(delta if cfg.grading == "margin"
                                   else MAX_START_RADIUS * delta, 0.0, MAX_START_RADIUS))
        if (u + 1) % max(1, updates // 10) == 0 or u == 0:
            entry = {"phase": label, "update": u + 1, "mean_episode_length": mean_len}
            extra = ""
            if negative:
                entry.update({"graded_loss": round(delta, 3), "start_radius": round(radius, 3)})
                extra = f"  graded loss {delta:.2f}  venture radius {radius:.2f}"
            log.append(entry)
            print(f"    {label:9s} update {u + 1:4d}/{updates}  "
                  f"mean episode length {mean_len:7.1f}{extra}")
        if step_budget is not None and env_steps >= step_budget:
            print(f"    {label:9s} step budget reached at update {u + 1} ({env_steps} steps)")
            break
    return float(np.mean(recent)) if recent else 0.0, delta, radius, env_steps


def run(cfg: Config, verbose: bool = True) -> dict:
    rng = np.random.default_rng(cfg.seed)
    env = gym.make("CartPole-v1")
    env.reset(seed=cfg.seed)
    net = SineNet([4, cfg.hidden, 2], np.random.default_rng(cfg.seed + 1000))
    log: list[dict] = []
    started = time.time()

    result: dict = {"seed": cfg.seed, "config": cfg.__dict__.copy()}
    result["untrained"] = evaluate(net, cfg, cfg.eval_episodes, 10_000)
    if verbose:
        print(f"  untrained                      reward {result['untrained']['mean']:7.1f}")

    # ---- phase 1: fail on purpose -------------------------------------
    opt = Adam(net, lr=cfg.neg_lr, act_lr=cfg.neg_lr / 10.0)
    fail_len, delta, radius, neg_steps = run_phase(env, net, opt, cfg, rng, cfg.neg_updates,
                                                   True, cfg.neg_entropy, "negative", log)
    result["failure_episode_length"] = fail_len
    result["failure_graded_loss"] = delta
    result["final_start_radius"] = radius
    result["failure_state_dependence"] = state_dependence(net, cfg)
    result["after_negative"] = evaluate(net, cfg, cfg.eval_episodes, 10_000)
    if verbose:
        sd = result["failure_state_dependence"]
        print(f"  after negative phase           reward {result['after_negative']['mean']:7.1f}"
              f"   (fail length {fail_len:.1f}, graded loss {delta:.2f}, radius {radius:.2f}, "
              f"majority action {sd['majority_action_share']:.0%}, "
              f"anti-balance {sd['anti_balance_agreement']:.0%})")

    # ---- phase 2: invert ----------------------------------------------
    probe = rng.normal(size=(256, 4)) * OBS_SCALE
    before = net.forward(probe, train=False)
    net.invert()
    after = net.forward(probe, train=False)
    result["inversion_max_error"] = float(np.abs(after + before).max())
    result["after_invert"] = evaluate(net, cfg, cfg.final_eval_episodes, 10_000)
    if verbose:
        print(f"  after INVERSION (no training)  reward {result['after_invert']['mean']:7.1f}"
              f"   (negation error {result['inversion_max_error']:.1e})")

    # ---- phase 3: fine-tune on the real reward -------------------------
    opt = Adam(net, lr=cfg.pos_lr, act_lr=cfg.pos_lr / 10.0)   # signs just flipped
    _, _, _, pos_steps = run_phase(env, net, opt, cfg, rng, cfg.pos_updates, False,
                                   cfg.pos_entropy, "positive", log)
    result["env_steps"] = {"negative": neg_steps, "positive": pos_steps,
                           "total": neg_steps + pos_steps}
    result["after_finetune"] = evaluate(net, cfg, cfg.final_eval_episodes, 20_000)
    result["activation_parameters"] = net.act_report()
    result["log"] = log
    result["seconds"] = round(time.time() - started, 1)
    if verbose:
        print(f"  after fine-tune                reward {result['after_finetune']['mean']:7.1f}"
              f"   over {cfg.final_eval_episodes} episodes"
              f"   {'SOLVED' if result['after_finetune']['mean'] >= SOLVED else ''}")
    env.close()
    return result


def run_control(cfg: Config, step_budget: int, verbose: bool = True) -> dict:
    """The comparison: the same network and the same number of environment
    steps, trained only on the real reward - no failure phase, no inversion."""
    rng = np.random.default_rng(cfg.seed)
    env = gym.make("CartPole-v1")
    env.reset(seed=cfg.seed)
    net = SineNet([4, cfg.hidden, 2], np.random.default_rng(cfg.seed + 1000))
    opt = Adam(net, lr=cfg.pos_lr, act_lr=cfg.pos_lr / 10.0)
    log: list[dict] = []
    started = time.time()
    updates = max(1, int(np.ceil(step_budget / cfg.pos_batch_steps)) * 4)
    _, _, _, steps = run_phase(env, net, opt, cfg, rng, updates, False, cfg.pos_entropy,
                               "control", log, step_budget=step_budget)
    out = {"seed": cfg.seed, "env_steps": steps,
           "after_training": evaluate(net, cfg, cfg.final_eval_episodes, 20_000),
           "log": log, "seconds": round(time.time() - started, 1)}
    if verbose:
        print(f"  control (no 2NRL)              reward {out['after_training']['mean']:7.1f}")
    env.close()
    return out


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--seeds", type=int, nargs="+", default=[0])
    p.add_argument("--neg-updates", type=int, default=Config.neg_updates)
    p.add_argument("--pos-updates", type=int, default=Config.pos_updates)
    p.add_argument("--fixed-starts", action="store_true",
                   help="do not venture out with the failure delta (shows the degenerate failure)")
    p.add_argument("--no-delta-weights", action="store_true",
                   help="do not weight each failure by its delta")
    p.add_argument("--grading", choices=["margin", "speed"], default="margin",
                   help="margin: venture out by |target - achieved| (the graded loss); "
                        "speed: the legacy ratio that saturates")
    p.add_argument("--control", action="store_true", help="also run the no-2NRL comparison")
    p.add_argument("--out", default=None, help="write the results as JSON")
    args = p.parse_args()

    runs, controls = [], []
    for seed in args.seeds:
        cfg = Config(seed=seed, neg_updates=args.neg_updates, pos_updates=args.pos_updates,
                     adaptive_starts=not args.fixed_starts,
                     weight_by_delta=not args.no_delta_weights,
                     grading=args.grading)
        print(f"\n=== 2NRL, seed {seed} "
              f"({'delta-driven' if cfg.adaptive_starts else 'standard'} negative-phase starts) ===")
        runs.append(run(cfg))
        if args.control:
            print(f"--- control, seed {seed} (matched {runs[-1]['env_steps']['total']} steps) ---")
            controls.append(run_control(cfg, runs[-1]["env_steps"]["total"]))

    print("\n" + "=" * 78)
    stages = [("untrained", "untrained"), ("after_negative", "trained to fail"),
              ("after_invert", "INVERTED (no training)"), ("after_finetune", "fine-tuned")]
    print(f"{'stage':<26}" + "".join(f"{'seed ' + str(r['seed']):>12}" for r in runs) + f"{'mean':>12}")
    for key, label in stages:
        vals = [r[key]["mean"] for r in runs]
        print(f"{label:<26}" + "".join(f"{v:12.1f}" for v in vals) + f"{np.mean(vals):12.1f}")
    if controls:
        vals = [c["after_training"]["mean"] for c in controls]
        print(f"{'control (no 2NRL)':<26}" + "".join(f"{v:12.1f}" for v in vals) + f"{np.mean(vals):12.1f}")
    print("=" * 78)

    if args.out:
        with open(args.out, "w") as fh:
            json.dump({"runs": runs, "controls": controls}, fh, indent=2)
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
